name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        cache: 
        - true
        - false
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ runner.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        repository: Randomblock1/FleetsBGone
        submodules: true
        
    - name: Prepare Theos
      # Don't use @main in production, this repo is specifically for testing it.
      uses: beerpiss/theos-action@main
      with:
        cache: ${{ matrix.cache }}
        cache-dir-theos: ${{ github.workspace }}/theos
        cache-dir-sdks: ${{ github.workspace }}/theos/sdks
      
    - name: Build package
      run: |
        rm -f packages/*
        make package FINALPACKAGE=1
 
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: 'Package'
        path: ${{ github.workspace }}/packages/*.deb
